server:
  port: 8080
spring:
  datasource:
    platform: h2
    url: jdbc:h2:mem:Test_DB
    username: sa
    password:
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
#H2-InMemoryDB -> http://localhost:8080/h2-console